# Generated by Django 4.2.10 on 2024-02-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='poi_id',
            field=models.CharField(max_length=100, verbose_name='poi external id'),
        ),
    ]
